package pnserver

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"
)

const nodeProfileVersion = 1

var (
	ErrNodeProfileNotFound = errors.New("node profile is not configured")
	ErrAlreadyProvisioned  = errors.New("proxy services are already configured")
)

// NodeProfile is sensitive connection material fetched after pairing. It is
// never embedded in a *.pdn file and intentionally contains no routing
// policy, TUN settings, DNS rules, or generated client configuration.
type NodeProfile struct {
	Version   int            `json:"version"`
	ServerID  string         `json:"server_id"`
	UpdatedAt time.Time      `json:"updated_at"`
	Protocols []NodeProtocol `json:"protocols"`
}

type NodeProtocol struct {
	ID           string         `json:"id"`
	Type         string         `json:"type"`
	DisplayName  string         `json:"display_name"`
	VLESSReality *VLESSReality  `json:"vless_reality,omitempty"`
	Hysteria2    *Hysteria2Node `json:"hysteria2,omitempty"`
}

type VLESSReality struct {
	Server     string `json:"server"`
	ServerPort int    `json:"server_port"`
	UUID       string `json:"uuid"`
	Flow       string `json:"flow"`
	ServerName string `json:"server_name"`
	PublicKey  string `json:"public_key"`
	ShortID    string `json:"short_id"`
}

type Hysteria2Node struct {
	Server                     string `json:"server"`
	ServerPort                 int    `json:"server_port"`
	Password                   string `json:"password"`
	ObfsType                   string `json:"obfs_type"`
	ObfsPassword               string `json:"obfs_password"`
	ServerName                 string `json:"server_name"`
	CertificatePublicKeySHA256 string `json:"certificate_public_key_sha256"`
}

func (s *Store) nodePath() string { return filepath.Join(s.Dir, "node.json") }

// ImportSingb migrates the public client-side connection material generated by
// the existing singb script without rotating or exposing server private keys.
func (s *Store) ImportSingb(configPath, secretsPath string) (NodeProfile, error) {
	config, err := readRestrictedEnv(configPath)
	if err != nil {
		return NodeProfile{}, fmt.Errorf("read singb config: %w", err)
	}
	secrets, err := readRestrictedEnv(secretsPath)
	if err != nil {
		return NodeProfile{}, fmt.Errorf("read singb state: %w", err)
	}
	value := func(key string) string {
		if v := config[key]; v != "" {
			return v
		}
		return secrets[key]
	}
	required := []string{
		"SERVER_IP", "XRAY_PORT", "XRAY_UUID", "XRAY_PUBLIC_KEY", "XRAY_SHORT_ID", "XRAY_SNI",
		"HY2_PORT", "HY2_PASSWORD", "HY2_OBFS_TYPE", "HY2_OBFS_PASSWORD", "HY2_TLS_CERT_PUBKEY_SHA256",
	}
	for _, key := range required {
		if value(key) == "" {
			return NodeProfile{}, fmt.Errorf("singb state is missing %s", key)
		}
	}
	xrayPort, err := parsePort(value("XRAY_PORT"))
	if err != nil {
		return NodeProfile{}, fmt.Errorf("XRAY_PORT: %w", err)
	}
	hy2Port, err := parsePort(value("HY2_PORT"))
	if err != nil {
		return NodeProfile{}, fmt.Errorf("HY2_PORT: %w", err)
	}

	profile := NodeProfile{Protocols: []NodeProtocol{
		{
			ID: "reality", Type: "vless-reality", DisplayName: "Reality",
			VLESSReality: &VLESSReality{
				Server: value("SERVER_IP"), ServerPort: xrayPort,
				UUID: value("XRAY_UUID"), Flow: "xtls-rprx-vision",
				ServerName: value("XRAY_SNI"), PublicKey: value("XRAY_PUBLIC_KEY"),
				ShortID: value("XRAY_SHORT_ID"),
			},
		},
		{
			ID: "hy2", Type: "hysteria2", DisplayName: "Hysteria2",
			Hysteria2: &Hysteria2Node{
				Server: value("SERVER_IP"), ServerPort: hy2Port,
				Password: value("HY2_PASSWORD"), ObfsType: value("HY2_OBFS_TYPE"),
				ObfsPassword: value("HY2_OBFS_PASSWORD"), ServerName: value("SERVER_IP"),
				CertificatePublicKeySHA256: value("HY2_TLS_CERT_PUBKEY_SHA256"),
			},
		},
	}}
	if err := s.SaveNodeProfile(profile); err != nil {
		return NodeProfile{}, err
	}
	return s.LoadNodeProfile()
}

func (s *Store) SaveNodeProfile(profile NodeProfile) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	state, err := s.loadState()
	if err != nil {
		return err
	}
	if len(profile.Protocols) == 0 {
		return errors.New("node profile must contain at least one protocol")
	}
	profile.Version = nodeProfileVersion
	profile.ServerID = state.ServerID
	profile.UpdatedAt = s.now()
	return writePrivateJSON(s.nodePath(), profile)
}

func (s *Store) LoadNodeProfile() (NodeProfile, error) {
	s.mu.Lock()
	defer s.mu.Unlock()
	b, err := os.ReadFile(s.nodePath())
	if errors.Is(err, os.ErrNotExist) {
		return NodeProfile{}, ErrNodeProfileNotFound
	}
	if err != nil {
		return NodeProfile{}, err
	}
	var profile NodeProfile
	if err := jsonUnmarshalStrict(b, &profile); err != nil {
		return NodeProfile{}, fmt.Errorf("decode node profile: %w", err)
	}
	if profile.Version != nodeProfileVersion || profile.ServerID == "" || len(profile.Protocols) == 0 {
		return NodeProfile{}, errors.New("node profile is invalid or unsupported")
	}
	return profile, nil
}

func readRestrictedEnv(path string) (map[string]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	values := map[string]string{}
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, raw, ok := strings.Cut(line, "=")
		if !ok || !validEnvKey(key) {
			return nil, fmt.Errorf("unsupported line %q", line)
		}
		value, err := decodeShellWord(raw)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", key, err)
		}
		values[key] = value
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	return values, nil
}

func validEnvKey(key string) bool {
	if key == "" {
		return false
	}
	for i, r := range key {
		if !((r >= 'A' && r <= 'Z') || r == '_' || (i > 0 && r >= '0' && r <= '9')) {
			return false
		}
	}
	return true
}

// decodeShellWord supports the single-value output of bash printf %q used by
// singb. It never evaluates substitutions or executes shell syntax.
func decodeShellWord(raw string) (string, error) {
	if raw == "''" || raw == `""` {
		return "", nil
	}
	if len(raw) >= 2 && raw[0] == '\'' && raw[len(raw)-1] == '\'' {
		return raw[1 : len(raw)-1], nil
	}
	if len(raw) >= 2 && raw[0] == '"' && raw[len(raw)-1] == '"' {
		return strconv.Unquote(raw)
	}
	if strings.ContainsAny(raw, "`$;&|<>()\n\r") {
		return "", errors.New("unsafe shell syntax")
	}
	var out strings.Builder
	escaped := false
	for _, r := range raw {
		if escaped {
			out.WriteRune(r)
			escaped = false
		} else if r == '\\' {
			escaped = true
		} else {
			out.WriteRune(r)
		}
	}
	if escaped {
		return "", errors.New("trailing escape")
	}
	return out.String(), nil
}

func parsePort(value string) (int, error) {
	port, err := strconv.Atoi(value)
	if err != nil || port < 1 || port > 65535 {
		return 0, errors.New("port must be between 1 and 65535")
	}
	return port, nil
}
