#!/usr/bin/env bash
# sbtally cutover installer — replaces SFM with a standalone sing-box CLI (TUN)
# plus the sbtally stats daemon, both under launchd.
#
# NOTE: PendingNet.app 现在自己带 sbtally、自己按引擎的生命周期起停它（见
# app/SBTally/PendingNetStatsDaemon.swift）。这个脚本装的用户级 LaunchAgent
# 是 App 之前那条手工路径；App 下次启动引擎时会把它 bootout 并把 plist 改名挪走
# （改回 .plist 就能还原），免得两个采集器抢同一个 7777 和同一个 SQLite 库。
# 也就是说：用 PendingNet.app 的机器不需要再跑这个脚本。
#
# Usage:  deploy/install.sh <master.json> <clash-secret>
#
# Prereqs:
#   - sing-box on PATH            (brew install sing-box)
#   - Go toolchain                (to build sbtally)
#   - SFM / any other TUN VPN QUIT — two TUN providers conflict
#   - <master.json> generated by: sbtally config generate --vps ... --out master.json
#   - <clash-secret> matching experimental.clash_api.secret in that config
#
# This script performs privileged actions (sudo, launchctl). Review before running.
# It is verified at real-machine cutover, not in CI.
set -euo pipefail

MASTER="${1:-}"
SECRET="${2:-}"
if [[ -z "$MASTER" || -z "$SECRET" ]]; then
    echo "usage: deploy/install.sh <master.json> <clash-secret>" >&2
    exit 2
fi
[[ -f "$MASTER" ]] || { echo "no such file: $MASTER" >&2; exit 1; }

SINGBOX="$(command -v sing-box || true)"
[[ -n "$SINGBOX" ]] || { echo "sing-box not on PATH — brew install sing-box" >&2; exit 1; }

REPO="$(cd "$(dirname "$0")/.." && pwd)"
PLIST_DIR="$REPO/deploy/launchd"
UID_NUM="$(id -u)"

echo "==> Validating master config with sing-box check"
"$SINGBOX" check -c "$MASTER"

echo "==> Building sbtally"
( cd "$REPO" && go build -o /tmp/sbtally.bin ./cmd/sbtally )
sudo install -m 0755 /tmp/sbtally.bin /usr/local/bin/sbtally

echo "==> Installing master config -> /usr/local/etc/sbtally/master.json"
sudo mkdir -p /usr/local/etc/sbtally
sudo install -m 0644 "$MASTER" /usr/local/etc/sbtally/master.json

echo "==> Rule-sets: ownership + geosite-gfw"
sudo chown "$(id -un)":staff /usr/local/etc/sbtally
find /usr/local/etc/sbtally -maxdepth 1 -name '*.srs' -exec sudo chown "$(id -un)":staff {} +
if [[ ! -f /usr/local/etc/sbtally/geosite-gfw.srs ]]; then
    curl -sfm 30 -o /tmp/geosite-gfw.srs \
      https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/gfw.srs \
      || curl -sfm 30 -x http://127.0.0.1:2080 -o /tmp/geosite-gfw.srs \
      https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/sing/geo/geosite/gfw.srs
    install -m 0644 /tmp/geosite-gfw.srs /usr/local/etc/sbtally/
fi
sudo rm -rf /Applications/SBTally.app

echo "==> Installing sing-box LaunchDaemon (root), sing-box at $SINGBOX"
SINGBOX="$SINGBOX" perl -pe 's/__SINGBOX__/$ENV{SINGBOX}/g' \
    "$PLIST_DIR/io.sbtally.singbox.plist" | sudo tee /Library/LaunchDaemons/io.sbtally.singbox.plist >/dev/null
sudo chmod 0644 /Library/LaunchDaemons/io.sbtally.singbox.plist

echo "==> Installing sbtally LaunchAgent (user)"
mkdir -p "$HOME/Library/LaunchAgents"
SECRET="$SECRET" perl -pe 's/__SECRET__/$ENV{SECRET}/g' \
    "$PLIST_DIR/io.sbtally.daemon.plist" > "$HOME/Library/LaunchAgents/io.sbtally.daemon.plist"

echo "==> Loading sbtally daemon (user agent)"
launchctl bootout "gui/$UID_NUM/io.sbtally.daemon" 2>/dev/null || true
launchctl bootstrap "gui/$UID_NUM" "$HOME/Library/LaunchAgents/io.sbtally.daemon.plist"

# Two-phase cutover: with SBTALLY_NO_START=1 everything above runs while SFM is
# still up (safe — nothing touches the TUN). Then quit SFM and run the single
# command below to start the sing-box TUN daemon.
if [[ "${SBTALLY_NO_START:-0}" == "1" ]]; then
    cat <<EOF

==> Staged (SBTALLY_NO_START=1). sing-box TUN NOT started.
    Now: quit SFM, then run the switch:

      sudo launchctl bootout system/io.sbtally.singbox 2>/dev/null; \\
      sudo launchctl bootstrap system /Library/LaunchDaemons/io.sbtally.singbox.plist; \\
      sudo launchctl kickstart system/io.sbtally.singbox

    Rollback if connectivity doesn't return in ~30s: re-open SFM.
EOF
    exit 0
fi

echo "==> Starting sing-box (TUN, root). Quit SFM first if you haven't."
sudo launchctl bootout system/io.sbtally.singbox 2>/dev/null || true
sudo launchctl bootstrap system /Library/LaunchDaemons/io.sbtally.singbox.plist
sudo launchctl kickstart system/io.sbtally.singbox

cat <<EOF

==> Done. sing-box (TUN) and the sbtally daemon are running under launchd.

Verify:
  sbtally apps --since 1h          # real per-app traffic should appear
  curl -s 127.0.0.1:7777/api/summary?since=1h

Dashboard:
  cd app && xcodegen generate && open SBTally.xcodeproj   # then Run

Logs:
  /var/log/sbtally-singbox.log
  /tmp/sbtally-daemon.log

Uninstall:
  sudo launchctl bootout system/io.sbtally.singbox
  launchctl bootout gui/$UID_NUM/io.sbtally.daemon
  sudo rm /Library/LaunchDaemons/io.sbtally.singbox.plist ~/Library/LaunchAgents/io.sbtally.daemon.plist
EOF
